### ISSUE TITLE
Problem with upgrading image versions in liferay-mysql-elasticsearch docker-compose.yml file

### ISSUE THREAD

**Issue by java-boy** [igor-baiborodine/docker-liferay-portal-ce#5]
**Thanks for this great project, I kindly ask you to keep it updated and make it ready for the production environment👍** 

**I have updated images to the latest versions in docker-compose.yml and ran and setup database successfully, also the Liferay tables are created, but after restarting the containers and running for the second time I get the following errors:**

 Caused by: java.lang.NullPointerException
liferay_1        |      at com.liferay.portal.security.permission.StagingPermissionChecker.hasPermission(StagingPermissionChecker.java:114) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.kernel.security.permission.wrapper.PermissionCheckerWrapper.hasPermission(PermissionCheckerWrapper.java:101) ~[portal-kernel.jar:?]
liferay_1        |      at com.liferay.depot.internal.security.permission.wrapper.DepotPermissionCheckerWrapper.lambda$hasPermission$0(DepotPermissionCheckerWrapper.java:70) ~[?:?]
liferay_1        |      at com.liferay.depot.internal.security.permission.wrapper.DepotPermissionCheckerWrapper._hasPermission(DepotPermissionCheckerWrapper.java:238) ~[?:?]
liferay_1        |      at com.liferay.depot.internal.security.permission.wrapper.DepotPermissionCheckerWrapper.hasPermission(DepotPermissionCheckerWrapper.java:68) ~[?:?]
liferay_1        |      at com.liferay.portal.service.permission.GroupPermissionImpl._contains(GroupPermissionImpl.java:230) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.service.permission.GroupPermissionImpl.contains(GroupPermissionImpl.java:104) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.kernel.service.permission.GroupPermissionUtil.contains(GroupPermissionUtil.java:51) ~[portal-kernel.jar:?]
liferay_1        |      at com.liferay.portal.service.permission.LayoutPermissionImpl.containsWithoutViewableGroup(LayoutPermissionImpl.java:292) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.service.permission.LayoutPermissionImpl.containsWithoutViewableGroup(LayoutPermissionImpl.java:334) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.service.permission.LayoutPermissionImpl.containsWithViewableGroup(LayoutPermissionImpl.java:348) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.service.permission.LayoutPermissionImpl._contains(LayoutPermissionImpl.java:610) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.service.permission.LayoutPermissionImpl.contains(LayoutPermissionImpl.java:147) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.service.permission.LayoutPermissionImpl.contains(LayoutPermissionImpl.java:161) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.kernel.service.permission.LayoutPermissionUtil.contains(LayoutPermissionUtil.java:72) ~[portal-kernel.jar:?]
liferay_1        |      at com.liferay.portal.kernel.model.impl.DefaultLayoutTypeAccessPolicyImpl.isCustomizeLayoutAllowed(DefaultLayoutTypeAccessPolicyImpl.java:141) ~[portal-kernel.jar:?]
liferay_1        |      at com.liferay.portal.events.ServicePreAction._initThemeDisplay(ServicePreAction.java:1188) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.events.ServicePreAction.servicePre(ServicePreAction.java:169) ~[portal-impl.jar:?]
liferay_1        |      at com.liferay.portal.events.ServicePreAction.run(ServicePreAction.java:150) ~[portal-impl.jar:?]
liferay_1        |      ... 148 more
liferay_1        | 2021-09-03 13:20:20.876 ERROR [http-nio-8080-exec-1][error_jsp:529] User ID null
liferay_1        | 2021-09-03 13:20:20.878 ERROR [http-nio-8080-exec-1][error_jsp:530] Current URL /
liferay_1        | 2021-09-03 13:20:20.880 ERROR [http-nio-8080-exec-1][error_jsp:531] Referer null
liferay_1        | 2021-09-03 13:20:20.881 ERROR [http-nio-8080-exec-1][error_jsp:532] Remote address 127.0.0.1
liferay_1        | 2021-09-03 13:20:20.883 ERROR [http-nio-8080-exec-1][error_jsp:534] null
liferay_1        | 2021-09-03 13:20:20.901 ERROR [http-nio-8080-exec-1][error_jsp:529] User ID null
liferay_1        | 2021-09-03 13:20:20.902 ERROR [http-nio-8080-exec-1][error_jsp:530] Current URL /
liferay_1        | 2021-09-03 13:20:20.903 ERROR [http-nio-8080-exec-1][error_jsp:531] Referer null
liferay_1        | 2021-09-03 13:20:20.904 ERROR [http-nio-8080-exec-1][error_jsp:532] Remote address 127.0.0.1
liferay_1        | 2021-09-03 13:20:20.905 ERROR [http-nio-8080-exec-1][error_jsp:534] null
liferay_1        | 2021-09-03 13:20:20.906 ERROR [http-nio-8080-exec-1][InitFilter:62] java.lang.NullPointerException
liferay_1        | java.lang.NullPointerException: null
liferay_1        |      at org.apache.jsp.html.common.error_jsp._jspService(error_jsp.java:537) ~[?:?]
liferay_1        |      at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.43]
liferay_1        |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[servlet-api.jar:4.0.FR]

**And here is my docker-compose.yml :**

version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: liferay
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mnt/mysql/conf.d:/etc/mysql/conf.d
      - ./mnt/mysql/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - cluster.name=LiferayElasticsearchCluster
      - xpack.security.enabled=false
      - network.bind_host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  liferay:
    image: ibaiborodine/liferay-portal-ce:latest
    depends_on:
      - mysql
      - elasticsearch
    environment:
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY: 10
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 10
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: "com.mysql.cj.jdbc.Driver"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: "password"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: "root"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: "jdbc:mysql://mysql/liferay?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true&serverTimezone=GMT"
    ports:
      - "80:8080"
      - "11311:11311"
    volumes:
      - ./mnt/liferay/base:/etc/opt/liferay
      - lr-data:/opt/liferay/data/document_library

volumes:
  db-data:
  es-data:
  lr-data:

**Comment by igor-baiborodine** [comment]
Mehdi, thanks for letting me know. I will check it next week. Meanwhile, can you try using version 7.4.1-ga2 instead of the latest? I discovered that version 7.4.2-ga3 contains a bug, namely the admin panel is not rendered correctly. The official image from Liferay has the same issue.

**Comment by java-boy** [comment]
Thanks, Igor

I just deleted the container containing the latest image of Liferay (7.4.2 ga3) and made other containers with both 7.4.2 and 7.4.1, they both work well, but as you mentioned the admin panel in 7.4.2 does not render properly.
I will continue using 7.4.1 and waiting for the new version of Liferay to be fixed.
